#!/usr/bin/env python
import sys

if len(sys.argv) > 1:
    LOG_LEVEL = sys.argv[1]
else:
    LOG_LEVEL = 'info'

from kivy.config import Config
Config.set('kivy', 'log_level', LOG_LEVEL)

from ecto.eran.core import run
from ecto.main import MainWidget

from ecto.scoreloader import midi_to_txt

# midi_to_txt('rite')

run(MainWidget)
