config = {
    'PLANE_SPACING': 50,
    'LINE_SPACING': 5,
    'UNITS_PER_METER': 2.5,
    'UNITS_PER_TICK': 30./480.,
    'SELF_PLANE_DISTANCE': 8,
    'OSC_OUT_PORT': 5555,
    'VISIBLE_TICK_RANGE': 480 * 6
}
